# Default values for pyapp.

## Image Registry
registry: 509458535641.dkr.ecr.us-west-2.amazonaws.com
tag: latest

## App configuration
app:
  name: pythonapp
  replicas: 1
  pullPolicy: Always
  ## Service settings 
  service:
    ## Annotations for enabling prometheus scraping
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: /metrics
      prometheus.io/port: "80"
    type: NodePort
    externalPort: 80
    internalPort: 80
    name: http
  ## ALB ingress configuration
  ingress:
    enabled: true
    class: alb
    scheme: internet-facing
    host: app.hossanrose.com
