# Default values for pyapp.

registry: 509458535641.dkr.ecr.us-west-2.amazonaws.com
tag: latest
replicaCount: 1


app:
  name: pythonapp
  replicas: 1
  pullPolicy: Always
  service:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: /metrics
      prometheus.io/port: "80"
    type: NodePort
    externalPort: 80
    internalPort: 80
    name: http
  ingress:
    enabled: true
    class: alb
    scheme: internet-facing
    host: app.hossanrose.com
    path:
